import { BASE_URL } from '@shared/lib'
import type { Product } from './types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'issue-01-renaissance',
    title: 'Issue 01: Renaissance Dreams',
    description:
      'Welcome to the debut edition of our flagship publication. This issue explores the profound rebirth of classical aesthetics within the chaotic landscape of modern digital art. We delve deep into how 21st-century creators are reviving Renaissance techniques—sfumato, chiaroscuro, and golden ratio compositions—to bring soul back into algorithmic generations. Spanning over 120 pages of meticulously curated content, we feature exclusive long-form interviews with ten global visionaries who are redefining the boundaries of the canvas. This is more than a magazine; it is a collector’s artifact designed for those who find beauty in the intersection of history and innovation. From the weight of the silk-coated paper to the smell of the premium Dutch ink, every sensory detail has been engineered to provide an unparalleled reading experience that lingers long after the final page is turned.',
    price: 45,
    previewImage: `${BASE_URL}content/products/issue-01-renaissance/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-01-renaissance/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: '120 pages, Silk Paper 150gsm, Debossed Cover.',
    keys: ['MAGAZINE', 'ART PRINTS', 'SUBSCRIPTIONS'],
  },
  {
    id: '2',
    slug: 'issue-02-brutalist-vision',
    title: 'Issue 02: Brutalist Vision',
    description:
      'In this second installment, we shift our focus to the raw, uncompromising world of Brutalism. Often misunderstood as cold or sterile, we reveal the inherent honesty of exposed concrete and functionalist design. Our editorial team traveled across Eastern Europe and London to capture the most iconic structures that define this era, presenting them alongside modern web design philosophies that embrace "digital brutalism"—raw layouts, bold typography, and a rejection of unnecessary decoration. The issue includes a specialized supplement on architectural photography, teaching readers how to find light in the shadows of monolithic forms. We also explore how the utilitarian spirit of the 1950s is being reimagined in contemporary fashion and furniture. This volume is a tribute to the bold, the structural, and the unyielding. It challenges the reader to look past the surface and find the rhythmic beauty in the heavy, the gray, and the permanent.',
    price: 45,
    previewImage: `${BASE_URL}content/products/issue-02-brutalist-vision/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-02-brutalist-vision/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Heavyweight Matte Cover, Silver Foil Accents.',
    keys: ['BOOKS', 'MAGAZINE', 'KINDLING'],
  },
  {
    id: '3',
    slug: 'issue-03-neon-noir-cities',
    title: 'Issue 03: Neon Noir Cities',
    description:
      'Issue 03 takes you on a cinematic journey through the world’s most luminous nocturnes. We explore the "Neon Noir" aesthetic, a subgenre that blends the gritty mystery of 1940s film noir with the high-tech, low-life atmosphere of cyberpunk futures. This edition features breathtaking night-time photography from Tokyo, Hong Kong, and Seoul, highlighting the loneliness and electricity of the modern megalopolis. Our contributors discuss the psychological impact of artificial light on urban dwelling and how the glow of the neon sign became a universal symbol of hope and despair. Included is a special focus on "Kindling" the creative spark during late-night hours, featuring essays from writers who only work when the sun is down. The pages are printed with a special high-gloss finish to make the colors pop against the deep black backgrounds, ensuring that every image feels like a glowing screen. This is an essential volume for anyone captivated by the mystery of the night and the neon pulse of the future.',
    price: 50,
    previewImage: `${BASE_URL}content/products/issue-03-neon-noir-cities/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-03-neon-noir-cities/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'UV-Reactive Ink, 140 pages, High-Gloss Finish.',
    keys: ['MAGAZINE', 'ART PRINTS', 'KINDLING'],
  },
  {
    id: '4',
    slug: 'issue-04-organic-foundations',
    title: 'Issue 04: Organic Foundations',
    description:
      'Sustainability is no longer a trend; it is the foundation of the future. Issue 04: Organic Foundations examines the symbiotic relationship between human design and the natural world. We investigate how bio-mimesis is changing the way we build our homes, craft our furniture, and even print our books. This issue is a masterclass in textures—from the rough grain of reclaimed timber to the delicate veins of a leaf. We showcase designers who are using mushroom-based materials and recycled plastics to create high-end luxury items that leave zero footprint. The central essay explores the concept of "Kindling" the earth—how we can reignite our connection to the soil in a digital-first world. Printed entirely on 100% post-consumer recycled paper with soy-based inks, this edition practices what it preaches. It is a soft-spoken, beautiful call to action for the conscious collector who values the longevity of the planet as much as the quality of their library.',
    price: 42,
    previewImage: `${BASE_URL}content/products/issue-04-organic-foundations/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-04-organic-foundations/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: '100% Recycled Paper, Soy Inks, Embossed Leaf Motif.',
    keys: ['BOOKS', 'SUBSCRIPTIONS', 'KINDLING'],
  },
  {
    id: '5',
    slug: 'issue-05-the-typographic-soul',
    title: 'Issue 05: The Typographic Soul',
    description:
      'Typography is the invisible architecture of thought. In our fifth issue, we pull back the curtain on the world of fonts, letters, and the history of the written word. From the rigid discipline of the Swiss Style to the chaotic expressive freedom of variable digital fonts, we explore how the way we dress our words changes their meaning. This issue features a comprehensive history of the Gutenberg press and its modern digital successors. We speak with type designers who spend years perfecting a single serif and investigate the psychological power of brand identities. A special section is dedicated to "Art Prints" featuring iconic typographic posters that have defined political movements and cultural eras. Whether you are a professional designer or a lover of literature, this issue will change the way you see every billboard, book, and screen you encounter. It is a celebration of the character, the stroke, and the white space that defines our communication. Includes a limited-edition specimen booklet.',
    price: 45,
    previewImage: `${BASE_URL}content/products/issue-05-the-typographic-soul/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-05-the-typographic-soul/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Includes Typography Specimen Booklet, 130 pages.',
    keys: ['MAGAZINE', 'ART PRINTS', 'BOOKS'],
  },
  {
    id: '6',
    slug: 'issue-06-analog-rituals',
    title: 'Issue 06: Analog Rituals',
    description:
      'In an age of instant gratification and digital cloud storage, the sixth issue of our series celebrates the beauty of the physical. "Analog Rituals" is an ode to the tactile—the crackle of a vinyl record, the grain of 35mm film, and the weight of a fountain pen in hand. we explore why modern creators are fleeing back to the "obsolete" technologies of the past. This issue features a curated guide to the best independent bookshops and record stores across the globe. We talk to artisans who still bind books by hand and photographers who spend days in the darkroom to produce a single print. The theme of "Kindling" is present throughout, as we discuss how analog processes fire the imagination in ways that digital shortcuts cannot. This volume is a slow-burn experience, designed to be read away from any screen, perhaps with a record playing in the background. It is an invitation to slow down, to touch, to listen, and to truly own the media you consume. This issue comes with a set of three high-quality postcards.',
    price: 55,
    previewImage: `${BASE_URL}content/products/issue-06-analog-rituals/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-06-analog-rituals/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Textured Linen Cover, 110 pages, Includes 3 Postcards.',
    keys: ['BOOKS', 'MAGAZINE', 'KINDLING'],
  },
  {
    id: '7',
    slug: 'issue-07-virtual-realities',
    title: 'Issue 07: Virtual Realities',
    description:
      'What happens to the soul when the body enters the machine? Issue 07: Virtual Realities explores the frontier of the Metaverse, digital identity, and the blurring lines between the physical and the simulated. We look at how digital fashion is becoming a trillion-dollar industry and how architects are building impossible structures in virtual space. This issue features a debate on the future of "Subscriptions" in a world where you may never truly "own" the assets you buy. We also showcase "Art Prints" that were generated by AI but finished by human hands, questioning the definition of authorship in the 21st century. Despite the high-tech subject matter, the physical magazine remains a grounding force, utilizing metallic papers and holographic foils to bridge the gap between two worlds. It is a deep dive into the code that is starting to write our reality, providing a critical perspective on the utopian promises and dystopian risks of our digital trajectory. Includes a QR code for an exclusive AR experience.',
    price: 48,
    previewImage: `${BASE_URL}content/products/issue-07-virtual-realities/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-07-virtual-realities/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Holographic Foil Cover, 145 pages, AR-enabled.',
    keys: ['MAGAZINE', 'SUBSCRIPTIONS', 'ART PRINTS'],
  },
  {
    id: '8',
    slug: 'issue-08-monochrome-minimalism',
    title: 'Issue 08: Monochrome Minimalism',
    description:
      'There is a unique power in the absence of color. Issue 08: Monochrome Minimalism is a study of contrast, shadow, and the elegance of black and white. We look at high-fashion photography that strips away the distraction of color to focus on form, texture, and emotion. This issue features interviews with minimalist architects who believe that "less is more" and explores how living with fewer possessions can lead to a more "Kindled" and focused creative life. We examine the history of black and white cinema and its influence on modern visual storytelling. The production of this issue involved a specialized printing process that achieves the deepest blacks and the crispest whites possible on paper. It is a visual palate cleanser, a quiet and contemplative volume that stands out through its simplicity. For collectors, this issue is a staple of the library—a timeless piece of design that remains relevant across any trend. It is the ultimate expression of our dedication to high-quality "Art Prints" and editorial excellence.',
    price: 40,
    previewImage: `${BASE_URL}content/products/issue-08-monochrome-minimalism/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-08-monochrome-minimalism/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'High-Contrast BW Printing, 120 pages.',
    keys: ['MAGAZINE', 'ART PRINTS', 'BOOKS'],
  },
  {
    id: '9',
    slug: 'issue-09-the-street-aesthetic',
    title: 'Issue 09: The Street Aesthetic',
    description:
      'From the pavement to the podium, Issue 09: The Street Aesthetic tracks the rise of subcultural movements into the highest echelons of luxury. We go inside the studios of the world’s most influential streetwear designers to understand how a t-shirt became a canvas for political and social commentary. This issue features a massive section on "Art Prints" born from graffiti and street art, showing how these once-marginalized forms are now being auctioned for millions. We also discuss the "Subscription" model of modern drops and the psychology of hype. Our writers explore how urban environments "Kindle" creativity through the constant friction of diverse cultures living in close proximity. This volume is loud, vibrant, and essential for anyone who wants to understand the visual language of the modern city. It is a tribute to the outsiders who became the insiders, changing the way we dress and think forever. This edition features a special matte-laminate cover that feels as durable as the culture it describes.',
    price: 45,
    previewImage: `${BASE_URL}content/products/issue-09-the-street-aesthetic/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-09-the-street-aesthetic/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Matte-Laminate Cover, 135 pages.',
    keys: ['MAGAZINE', 'ART PRINTS', 'SUBSCRIPTIONS'],
  },
  {
    id: '10',
    slug: 'issue-10-retro-futurism',
    title: 'Issue 10: Retro Futurism',
    description:
      'How did the past imagine the future? Issue 10: Retro Futurism looks back at the "Space Age" dreams of the 1950s and 60s, comparing them to our modern reality. We rediscover the beautiful, curved lines of Googie architecture and the bold, optimistic illustrations of mid-century science fiction "Books". This issue investigates why we are still obsessed with the aesthetics of the Apollo era and how that "Kindles" our current drive to reach Mars. We feature a gallery of concept cars that never were and homes that look like flying saucers. The editorial design of this volume is inspired by vintage technical manuals, using blueprint-style layouts and metallic ink accents. It is a nostalgic yet forward-looking exploration of the human desire to leave the earth and reach for the stars. Whether you are a fan of vintage sci-fi or modern aerospace design, this issue offers a comprehensive look at the dreams that fueled a generation and continue to inspire the tech giants of today. It is a celebration of the imagination unfettered by gravity.',
    price: 50,
    previewImage: `${BASE_URL}content/products/issue-10-retro-futurism/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-10-retro-futurism/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Metallic Ink Accents, 125 pages.',
    keys: ['BOOKS', 'MAGAZINE', 'KINDLING'],
  },
  {
    id: '11',
    slug: 'issue-11-the-unseen-traveler',
    title: 'Issue 11: The Unseen Traveler',
    description:
      'Travel is about more than destinations; it is about a shift in perspective. Issue 11: The Unseen Traveler takes you off the beaten path to find the "Hidden Gems" of the architectural world. We visit brutalist relics in the mountains of Bulgaria, minimalist retreats in the forests of Japan, and hidden art galleries in the heart of Mexico City. This issue serves as a masterclass in travel photography, with a focus on capturing the "Soul" of a place rather than just its landmarks. We discuss the ethics of tourism and the rise of "Slow Travel" subscriptions that allow for deeper immersion in local cultures. Every page is a "Kindling" for your next adventure, encouraging a curiosity that goes beyond the tourist brochure. The paper stock for this issue is a special off-white ivory that feels like an old explorer’s journal, and the binding is designed to lay perfectly flat, making it the perfect companion for your coffee table or your backpack. It is a guide for the modern nomad who values authenticity over accessibility.',
    price: 45,
    previewImage: `${BASE_URL}content/products/issue-11-the-unseen-traveler/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-11-the-unseen-traveler/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Ivory Uncoated Paper, Lay-Flat Binding.',
    keys: ['BOOKS', 'MAGAZINE', 'SUBSCRIPTIONS'],
  },
  {
    id: '12',
    slug: 'issue-12-generative-logic',
    title: 'Issue 12: Generative Logic',
    description:
      'For our final issue of the annual cycle, we hand the controls over to the algorithm. Issue 12: Generative Logic is an experimental volume where the layout, the color palettes, and even some of the editorial content were produced via procedural generation. We examine the rise of the "Kindling" AI—how machine learning is being used to spark new ideas in human creators rather than replacing them. This issue features a deep dive into the world of NFT "Art Prints" and the "Subscription" economy of digital assets. We talk to philosophers who question if an algorithm can truly create "Art" and to developers who are building the creative tools of the next decade. To make this issue truly unique, we printed 5,000 different covers, each one a unique variation generated by a custom script. This is a snapshot of a moment in time where human and machine are learning to dance together, creating a beautiful, chaotic, and utterly new form of expression. It is a fitting end to the year and a bold look at what comes next.',
    price: 60,
    previewImage: `${BASE_URL}content/products/issue-12-generative-logic/preview.webp`,
    bannerImage: `${BASE_URL}content/products/issue-12-generative-logic/banner.webp`,
    images: [
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-1.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-2.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-3.webp`,
      `${BASE_URL}content/products/issue-01-renaissance/issue-01-4.webp`,
    ],
    details: 'Unique Generative Cover for every copy, 150 pages.',
    keys: ['MAGAZINE', 'KINDLING', 'SUBSCRIPTIONS'],
  },
]
